@FMLab.Aspnet.CleanArchitecture.Api_HostAddress = https://localhost:44356

POST {{FMLab.Aspnet.CleanArchitecture.Api_HostAddress}}/entities?name=Fagner

###

GET {{FMLab.Aspnet.CleanArchitecture.Api_HostAddress}}/entities?page=1&pageSize=5